spring.application.name=budgeting

## Utilizando Gemini pois o OpenAi nao oferece mais token gratuito.
## Comandos OpenAi funcionam com Gemini utilizando a url
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai

spring.ai.openai.chat.options.model=gemini-3.6-flash
spring.ai.openai.chat.options.temperature=0.8
spring.ai.openai.chat.options.response-format.type=TEXT