spring.application.name=budgeting

## Utilizando Gemini pois o OpenAi nao oferece mais token gratuito.
## Comandos OpenAi funcionam com Gemini utilizando a url
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai

spring.ai.openai.chat.options.model=gemini-3.6-flash
spring.ai.openai.chat.options.temperature=0.8
spring.ai.openai.chat.options.response-format.type=TEXT

spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=TEXT
spring.ai.openai.audio.transcription.options.prompt=Áudio em português brasileiro. \
  Áudio contém descrição de gastos financeiros. \
  As frase geralmente contém: \
    - um valor em reais (número + "reais"); \
    - uma ação (gastei, comprei, paguei); \
    -um local ou estabelecimento (mercado, farmácia, restaurante, loja, etc.).

logging.level.org.springframework.ai=DEBUG